name: React CI/CD Pipeline

# Trigger the workflow on pushes and pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Define the jobs
jobs:
  build:
    name: Build and Test React App
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test -- --watchAll=false

      # Build the project
      - name: Build Project
        run: npm run build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build  # Run only after the build job completes successfully

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
