name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      # Build the project
      - name: Build Project
        working-directory: ./frontend
        run: |
          echo "Starting the build process..."
          CI=false npm run build || (echo "Build failed. Exiting." && exit 1)

      # Debug: Check Build Output
      - name: Debug Build Output
        working-directory: ./frontend
        run: |
          echo "Listing contents of ./frontend/build"
          ls -la ./build || echo "Build directory does not exist"

  deploy:
    name: Deploy React App to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Setup SSH for secure file transfer
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Clone the Repository on EC2
      - name: Clone Repository on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          sudo rm -rf /var/www/react-app
          sudo mkdir -p /var/www/react-app
          sudo chown -R ubuntu:ubuntu /var/www/react-app
          cd /var/www/react-app
          https://github.com/Ramgopalhyndavbollepalli/demo11.git
          exit
          EOF

      # Install and Build on EC2
      - name: Install and Build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/react-app/frontend
          npm install
          CI=false npm run build
          exit
          EOF

      # Start the React App
      - name: Start React App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/react-app/frontend/build
          pm2 stop react-app || true
          pm2 start serve --name react-app -- -s . -l 3000
          pm2 save
          exit
          EOF
