name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Navigate to the frontend directory and install dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      # Build the project
      - name: Build Project
        working-directory: ./frontend
        run: |
            CI=false npm run build


  deploy:
    name: Deploy React App to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy React App
    run: |
      ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
      pm2 stop react-app || true
      rm -rf /var/www/react-app/*
      mkdir -p /var/www/react-app
      exit
      EOF
      ls -la ./frontend/build
      scp -o StrictHostKeyChecking=no -r ./frontend/build/* ubuntu@${{ secrets.EC2_IP }}:/var/www/react-app/
      ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "ls -la /var/www/react-app"

      ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
      cd /var/www/react-app
      npm install
      pm2 start npm --name react-app -- start
      exit
      EOF

