name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy React App to EC2
    runs-on: ubuntu-latest

    steps:
      # Setup SSH for secure file transfer
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Clone Repository on EC2
      - name: Clone Repository on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          sudo rm -rf /var/www/react-app
          sudo mkdir -p /var/www/react-app
          sudo chown -R ubuntu:ubuntu /var/www/react-app
          cd /var/www/react-app
          git clone https://ramgopalhyndavbollepalli:${{ secrets.GITHUB_PAT }}@github.com/Ramgopalhyndavbollepalli/demo11.git .
          exit
          EOF

      # Install and Build on EC2
      - name: Install and Build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/react-app/frontend
          npm install
          CI=false npm run build
          exit
          EOF

      # Start React App on EC2
      - name: Start React App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/react-app/frontend/build
          pm2 stop react-app || true
          pm2 start serve --name react-app -- -s . -l 3000
          pm2 save
          exit
          EOF
