name: React CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      # Build the project
      - name: Build Project
        working-directory: ./frontend
        run: |
          CI=false npm run build

      # Debug: Check Build Output
      - name: Debug Build Output
        working-directory: ./frontend
        run: |
          echo "Contents of ./frontend"
          ls -la .
          echo "Contents of ./frontend/build"
          ls -la ./build || echo "Build directory does not exist"

  deploy:
    name: Deploy React App to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code again (required for the deploy step)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup SSH for secure file transfer
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Debug: Check EC2 Environment
      - name: Debug EC2 Environment
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          which pm2 || echo "PM2 not installed"
          ls -ld /var/www || echo "No permissions for /var/www"
          exit
          EOF

      # Deploy the React app to EC2
      - name: Deploy React App
        run: |
          # Ensure target directory is clean and exists
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          pm2 stop react-app || true
          sudo rm -rf /var/www/react-app
          sudo mkdir -p /var/www/react-app
          sudo chown -R ubuntu:ubuntu /var/www/react-app
          exit
          EOF

          # Transfer build files to EC2
          scp -o StrictHostKeyChecking=no -r ./frontend/build/* ubuntu@${{ secrets.EC2_IP }}:/var/www/react-app/

          # Start the React app using PM2
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          cd /var/www/react-app
          pm2 start serve --name react-app -- -s . -l 3000
          pm2 save
          exit
          EOF
